# Generated by Django 4.0.4 on 2022-05-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_manage_acc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountreg',
            name='marital_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widow')], max_length=100),
        ),
        migrations.AlterField(
            model_name='accountreg',
            name='prefix',
            field=models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], max_length=100),
        ),
    ]
