# Generated by Django 4.0.4 on 2022-05-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_manage_acc', '0002_alter_accountreg_marital_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountreg',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='accountreg',
            name='birth_date',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
    ]
