# Generated by Django 4.0.4 on 2022-05-30 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('create_manage_acc', '0002_remove_accountreg_user_accountreg_uuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountreg',
            old_name='uuser',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='user',
            field=models.ForeignKey(db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
