# Generated by Django 4.0.4 on 2022-05-31 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('create_manage_acc', '0005_alter_accountreg_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountreg',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
