# Generated by Django 4.0.4 on 2022-05-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_manage_acc', '0007_alter_bankaccount_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='balance_currency',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.PositiveBigIntegerField(),
        ),
    ]
