# Generated by Django 4.0.4 on 2022-05-31 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_manage_acc', '0008_remove_bankaccount_balance_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='balance',
            new_name='deposit',
        ),
    ]
