# Generated by Django 4.0.4 on 2022-05-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_manage_acc', '0009_rename_balance_bankaccount_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
