# Generated by Django 4.0.4 on 2022-05-31 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_manage_acc', '0010_bankaccount_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='balance',
        ),
    ]
