# Generated by Django 3.2.8 on 2022-06-01 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('For Review', 'For Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='For Review', max_length=100, null=True)),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('dp_percent', models.PositiveIntegerField(blank=True, null=True)),
                ('dp_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('loan_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('no_of_payments', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('civ_status', models.CharField(blank=True, choices=[('Married', 'Married'), ('Separated', 'Separated'), ('Single', 'Single'), ('Widower', 'Widower')], max_length=100, null=True)),
                ('unit_no', models.CharField(blank=True, max_length=100, null=True)),
                ('condo_name', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('subdiv_brgy', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('municip_prov', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('len_stay', models.CharField(blank=True, choices=[('Months', 'Months'), ('Years', 'Years')], max_length=100, null=True)),
                ('len_stay_num', models.IntegerField(blank=True, null=True)),
                ('home_own', models.CharField(blank=True, choices=[('Mortgage', 'Mortgage'), ('Rented', 'Rented'), ('Owned', 'Owned'), ('Used Free/Living with Parents/Relatives', 'Used Free/Living with Parents/Relatives')], max_length=100, null=True)),
                ('phone_type', models.CharField(blank=True, choices=[('Home', 'Home'), ('Mobile', 'Mobile')], max_length=100, null=True)),
                ('home_num', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_num', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=100, null=True, region=None)),
                ('email_add', models.CharField(blank=True, max_length=100, null=True)),
                ('prime_income', models.CharField(blank=True, choices=[('Employment', 'Employment'), ('Business', 'Business')], max_length=100, null=True)),
                ('emp_type', models.CharField(blank=True, choices=[('Local(Government)', 'Local(Government)'), ('Local(Private)', 'Local(Private)'), ('OFW Non-Immigrant(Government)', 'OFW Non-Immigrant(Government)'), ('OFW Non-Immigrant(Private)', 'OFW Non-Immigrant(Private)')], max_length=100, null=True)),
                ('emp_name', models.CharField(blank=True, max_length=100, null=True)),
                ('job_pos', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_tenure', models.CharField(blank=True, choices=[('Months', 'Months'), ('Years', 'Years')], max_length=100, null=True)),
                ('emp_tenure_num', models.IntegerField(blank=True, null=True)),
                ('emp_monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('emp_work_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bsns_type', models.CharField(blank=True, default='Self-Employed', max_length=100, null=True)),
                ('bsns_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bsns_tenure', models.CharField(blank=True, choices=[('Months', 'Months'), ('Years', 'Years')], max_length=100, null=True)),
                ('bsns_tenure_num', models.IntegerField(blank=True, null=True)),
                ('bsns_monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('bsns_work_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bsns_unit_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bsns_condo_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bsns_street', models.CharField(blank=True, max_length=100, null=True)),
                ('bsns_subdiv_brgy', models.CharField(blank=True, max_length=100, null=True)),
                ('bsns_city', models.CharField(blank=True, max_length=100, null=True)),
                ('bsns_municip_prov', models.CharField(blank=True, max_length=100, null=True)),
                ('bsns_country', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
