# Generated by Django 4.0.4 on 2022-05-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_borrower', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='app_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
