# Generated by Django 4.0.4 on 2022-06-02 16:48

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('loans_borrower', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='loan_tag',
            field=models.CharField(blank=True, choices=[('For Review', 'For Review'), ('Delinquent', 'Delinquent'), ('In-Loan Default', 'In-Loan Default'), ('Completed', 'Completed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='civ_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Separated', 'Separated'), ('Single', 'Single'), ('Widower', 'Widower')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='dp_amt',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='dp_percent',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='email_add',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='home_num',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='loan_amt',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='make',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='mobile_num',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=100, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='loans',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='no_of_payments',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='phone_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Mobile', 'Mobile')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='prime_income',
            field=models.CharField(choices=[('Employment', 'Employment'), ('Business', 'Business')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True),
        ),
    ]
