# Generated by Django 4.0.4 on 2022-06-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_borrower', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='dp_percent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='home_own',
            field=models.CharField(blank=True, choices=[('Mortgage', 'Mortgage'), ('Rented', 'Rented'), ('Owned', 'Owned'), ('Used Free/Living with Parents/Relatives', 'Used Free/Living with Parents/Relatives')], max_length=100, null=True),
        ),
    ]
