# Generated by Django 4.0.4 on 2022-05-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_borrower', '0002_alter_loans_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='app_no',
        ),
        migrations.RemoveField(
            model_name='loans',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='loans',
            name='int_rate',
        ),
        migrations.RemoveField(
            model_name='loans',
            name='next_due',
        ),
        migrations.RemoveField(
            model_name='loans',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='loans',
            name='rem_bal',
        ),
        migrations.AddField(
            model_name='loans',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='bsns_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='bsns_condo_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='bsns_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='bsns_monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='bsns_municip_prov',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='bsns_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='bsns_street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='bsns_subdiv_brgy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='bsns_tenure',
            field=models.CharField(blank=True, choices=[('Months', 'Months'), ('Years', 'Years')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='bsns_tenure_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='bsns_type',
            field=models.CharField(blank=True, default='Self-Employed', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='bsns_unit_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='bsns_work_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='civ_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Separated', 'Separated'), ('Single', 'Single'), ('Widower', 'Widower')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='condo_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='dp_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='dp_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='email_add',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='emp_monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='emp_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='emp_tenure',
            field=models.CharField(blank=True, choices=[('Months', 'Months'), ('Years', 'Years')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='emp_tenure_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='emp_type',
            field=models.CharField(blank=True, choices=[('Local(Government)', 'Local(Government)'), ('Local(Private)', 'Local(Private)'), ('OFW Non-Immigrant(Government)', 'OFW Non-Immigrant(Government)'), ('OFW Non-Immigrant(Private)', 'OFW Non-Immigrant(Private)')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='emp_work_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='home_own',
            field=models.CharField(blank=True, choices=[('Mortgage', 'Mortgage'), ('Owned', 'Owned'), ('Rented', 'Rented'), ('Owned', 'Owned'), ('Used Free/Living with Parents/Relatives', 'Used Free/Living with Parents/Relatives')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='job_pos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='len_stay',
            field=models.CharField(blank=True, choices=[('Months', 'Months'), ('Years', 'Years')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='len_stay_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='municip_prov',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='phone_type',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Mobile', 'Mobile')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='prime_income',
            field=models.CharField(blank=True, choices=[('Employment', 'Employment'), ('Business', 'Business')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='subdiv_brgy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='unit_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='loan_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
