# Generated by Django 4.0.4 on 2022-06-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_borrower', '0002_alter_loans_dp_percent_alter_loans_home_own'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='loan_docs',
            field=models.FileField(blank=True, null=True, upload_to='loan_docs/'),
        ),
    ]
