# Generated by Django 4.0.4 on 2022-06-02 16:53

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('loans_borrower', '0002_loans_loan_tag_alter_loans_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='home_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='mobile_num',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=100, null=True, region=None),
        ),
    ]
