# Generated by Django 4.0.4 on 2022-05-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_borrower', '0002_loans_app_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='app_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
