# Generated by Django 4.0.4 on 2022-05-31 19:16

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('loans_borrower', '0003_alter_loans_app_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='mobile_num',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=100, null=True, region=None),
        ),
    ]
