# Generated by Django 4.0.4 on 2022-06-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_borrower', '0003_alter_loans_home_num_alter_loans_mobile_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='home_own',
            field=models.CharField(choices=[('Mortgage', 'Mortgage'), ('Rented', 'Rented'), ('Owned', 'Owned'), ('Used Free/Living with Parents/Relatives', 'Used Free/Living with Parents/Relatives')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='len_stay',
            field=models.CharField(choices=[('Months', 'Months'), ('Years', 'Years')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='len_stay_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='municip_prov',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='street',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='subdiv_brgy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='unit_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
