# Generated by Django 3.2.9 on 2022-05-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_borrower', '0004_alter_loans_civ_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='home_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='mobile_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
