# Generated by Django 4.0.4 on 2022-06-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_borrower', '0004_alter_loans_city_alter_loans_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='loan_bal',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True),
        ),
    ]
