# Generated by Django 4.0.4 on 2022-06-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_borrower', '0005_loans_loan_bal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='loan_bal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
