# Generated by Django 4.0.4 on 2022-05-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_borrower', '0005_auto_20220529_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='status',
            field=models.CharField(choices=[('For Review', 'For Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='For Review', max_length=100, null=True),
        ),
    ]
